import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

/// Implementation of `#VerdictScenario`.
///
/// Expands to a `VerdictScenario`-conforming struct plus a `verdictEntry`
/// static that a ``ScenarioRegistry`` is built from:
///
/// ```swift
/// #VerdictScenario("checkout") {
///     Text("Total: $42.00")
/// }
/// ```
///
/// becomes a `CheckoutScenario` struct whose `body(state:)` is the trailing
/// closure, probed exactly as `@Verifiable` probes a view's `body` — the two
/// macros share ``BodyProbeWalk``, so an element is instrumented identically
/// whichever door it came through. A scenario that diverged from a view here
/// would make the same `Text` verifiable in one context and invisible in the
/// other, for no reason an author could see.
///
/// ### Why the expansion declares a type rather than a value
///
/// ``OracleHost`` is generic over `Scenario: VerdictScenario` so the scenario's
/// `Body` type survives into the hosted tree, which means the scenario must be
/// a nominal type — a value of existential type `any VerdictScenario` cannot
/// satisfy that constraint. Declaring the type is therefore not a stylistic
/// choice; it is the only expansion that can reach the harness.
public struct VerdictScenarioMacro: DeclarationMacro {
    public static func expansion(
        of node: some FreestandingMacroExpansionSyntax,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let nameLiteral = Self.firstStringLiteral(of: node) else {
            context.diagnose(
                Diagnostic(node: node, message: VerdictScenarioDiagnostic.nameIsNotAStringLiteral)
            )
            return []
        }

        guard let typeName = Self.typeName(forScenarioNamed: nameLiteral.value) else {
            // A name with no letters or digits cannot produce a Swift
            // identifier, and a generated type called `_Scenario` would collide
            // with the next such scenario. Reported rather than mangled: an
            // author who wrote an unusable name should be told, not given a type
            // whose name they cannot predict.
            context.diagnose(
                Diagnostic(
                    node: node,
                    message: VerdictScenarioDiagnostic.nameHasNoIdentifierCharacters(
                        found: nameLiteral.value
                    )
                )
            )
            return []
        }

        guard let closure = node.trailingClosure else {
            context.diagnose(
                Diagnostic(node: node, message: VerdictScenarioDiagnostic.noBodyClosure)
            )
            return []
        }

        // The closure's statements are probed with the SAME walk `@Verifiable`
        // uses, namespaced under the generated type so ids read
        // `CheckoutScenario.text.0` — the same shape a probed view produces.
        var walk = BodyProbeWalk(typeName: typeName)
        let probedStatements = CodeBlockItemListSyntax(
            closure.statements.map { item in
                guard let expression = item.item.as(ExprSyntax.self) else { return item }
                var copy = item
                copy.item = .expr(walk.rewrite(expression))
                return copy
            }
        )

        // `state` is named in the signature but not necessarily used by a body
        // that has no bindings, so it is spelled `_ state:` — an unused
        // parameter warning under `-warnings-as-errors` would make a perfectly
        // good scenario fail to build, and the author cannot edit generated
        // code to silence it.
        //
        // No `.verdictRoot(into:)` here: `OracleHost` owns the root, the sink,
        // the pinned environment and the viewport (see `VerdictScenario`), so a
        // scenario that installed its own root could be rendered under an
        // environment a verdict was never recorded against.
        return [
            """
            /// A `VerdictScenario` generated by `#VerdictScenario`.
            struct \(raw: typeName): VerdictScenario, Sendable {
                let name = \(raw: nameLiteral.sourceText)

                @MainActor @ViewBuilder
                func body(state _: ScenarioState) -> some View {
                    \(probedStatements.trimmed)
                }

                /// This scenario's registry entry. Name it in a
                /// `ScenarioRegistry` to make the scenario discoverable.
                static let verdictEntry = ScenarioEntry { \(raw: typeName)() }
            }
            """
        ]
    }

    /// The first unlabelled string-literal argument, with its value and its
    /// source text.
    ///
    /// The source text is kept so the generated `name` re-emits exactly what the
    /// author wrote, escapes included, rather than a re-quoted approximation of
    /// the decoded value.
    static func firstStringLiteral(
        of node: some FreestandingMacroExpansionSyntax
    ) -> (value: String, sourceText: String)? {
        for argument in node.arguments where argument.label == nil {
            guard let literal = argument.expression.as(StringLiteralExprSyntax.self),
                literal.segments.count == 1,
                let segment = literal.segments.first?.as(StringSegmentSyntax.self)
            else {
                // An interpolated name is rejected rather than accepted: the
                // value is not knowable at expansion time, so neither the type
                // name nor the registry key could be derived from it.
                return nil
            }
            return (segment.content.text, literal.description)
        }
        return nil
    }

    /// The Swift type name a scenario name expands to — `"checkout flow"` →
    /// `CheckoutFlowScenario`.
    ///
    /// Returns `nil` when the name yields no identifier characters at all, which
    /// the caller reports rather than mangling.
    ///
    /// The `Scenario` suffix is always appended, so a scenario named `"Text"`
    /// becomes `TextScenario` and cannot shadow a SwiftUI type inside its own
    /// expansion — a generated `struct Text` would make every `Text(…)` in the
    /// body resolve to the scenario itself.
    static func typeName(forScenarioNamed name: String) -> String? {
        var out = ""
        var capitalizeNext = true
        for character in name {
            if character.isLetter || character.isNumber {
                if capitalizeNext {
                    out.append(contentsOf: character.uppercased())
                    capitalizeNext = false
                } else {
                    out.append(character)
                }
            } else {
                // Any non-identifier character is a word boundary: a space, a
                // hyphen and an underscore all mean the same thing in a
                // human-written scenario name.
                capitalizeNext = true
            }
        }
        if out.isEmpty { return nil }
        // A leading digit is legal in a scenario name and not in an identifier.
        if out.first?.isNumber == true { out = "S" + out }
        return out + "Scenario"
    }
}

/// Diagnostics `#VerdictScenario` can emit at its use site.
///
/// Spelled as a value type with an explicit `messageID` for the same reason
/// ``VerdictMacroDiagnostic`` is: the text an author reads is a testable
/// constant rather than a literal duplicated into an assertion.
enum VerdictScenarioDiagnostic: DiagnosticMessage {
    case nameIsNotAStringLiteral
    case nameHasNoIdentifierCharacters(found: String)
    case noBodyClosure

    var message: String {
        switch self {
        case .nameIsNotAStringLiteral:
            return """
                '#VerdictScenario' needs its name as a plain string literal, because the \
                name becomes both the generated type and the key a verdict is filed \
                under — neither is knowable from an interpolated or computed string.
                """
        case .nameHasNoIdentifierCharacters(let found):
            return """
                '#VerdictScenario' cannot build a type name from '\(found)': it contains \
                no letters or digits. Give the scenario a name with at least one.
                """
        case .noBodyClosure:
            return """
                '#VerdictScenario' needs a trailing closure holding the view to verify. \
                Write it as '#VerdictScenario("name") { Text("hello") }'.
                """
        }
    }

    var severity: DiagnosticSeverity { .error }

    var diagnosticID: MessageID {
        switch self {
        case .nameIsNotAStringLiteral:
            return MessageID(domain: "VerdictUIMacros", id: "scenarioNameIsNotAStringLiteral")
        case .nameHasNoIdentifierCharacters:
            return MessageID(domain: "VerdictUIMacros", id: "scenarioNameHasNoIdentifierCharacters")
        case .noBodyClosure:
            return MessageID(domain: "VerdictUIMacros", id: "scenarioNoBodyClosure")
        }
    }
}
