import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

/// Implementation of `@Verifiable`.
///
/// Wave 4 Task 1 ships the attachment surface and its diagnostics; Task 2 adds
/// the body walk that attaches `.verdictProbe(id:role:)` to recognised element
/// expressions. The split is deliberate rather than incidental: the diagnostics
/// below are the part that decides whether a *misapplied* macro is legible, and
/// they can be specified and tested before there is any expansion to test.
///
/// What it generates today is one member: `verdictProbedBody`, the view's own
/// `body` wrapped in `.verdictRoot(into:)`. Task 2 replaces the passthrough with
/// the probed walk; the member's name and signature are the seam that lets that
/// happen without a consumer-visible change.
public struct VerifiableMacro: MemberMacro {
    /// Types `@Verifiable` accepts. A macro attached to an `enum` or an
    /// `actor` must say so at the attachment site — the alternative is an
    /// expansion that fails to compile deeper in generated code the author
    /// cannot see, which is the worst diagnostic a macro can produce.
    private static let supportedKeyword = "struct"

    /// - Parameter protocols: conformances the compiler wants this expansion to
    ///   satisfy. Unused: `@Verifiable` is declared `@attached(member)` with no
    ///   `conformances:` clause, so the compiler never asks it to supply one and
    ///   this always arrives empty. The parameter is present because the
    ///   `conformingTo:`-less overload is deprecated in SwiftSyntax 603 — and
    ///   under `-warnings-as-errors` a deprecation is a build failure, so the
    ///   shorter spelling does not compile here at all.
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let structDecl = declaration.as(StructDeclSyntax.self) else {
            context.diagnose(
                Diagnostic(
                    node: node,
                    message: VerdictMacroDiagnostic.notAStruct(
                        found: declaration.kindDescription
                    )
                )
            )
            return []
        }

        guard structDecl.hasBodyMember else {
            context.diagnose(
                Diagnostic(node: node, message: VerdictMacroDiagnostic.noBodyMember)
            )
            return []
        }

        // `verdictProbedBody` rather than a rewritten `body`: a member macro
        // cannot replace an existing member, and generating a second `body`
        // would be a redeclaration error. The harness reaches the probed tree
        // through this member; the view's own `body` stays untouched, so a
        // `@Verifiable` view renders identically in a real app.
        return [
            """
            /// The view's `body` with the VerdictUI root installed.
            ///
            /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
            /// attached, so this is a normal view everywhere else.
            func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                body.verdictRoot(into: sink)
            }
            """
        ]
    }
}

extension StructDeclSyntax {
    /// Whether the type declares a `body` for the macro to wrap.
    ///
    /// Checked by name rather than by resolving `View` conformance, because a
    /// macro runs before conformances are checked and cannot see whether the
    /// type is a `View` — the conformance may even arrive from an extension in
    /// another file. Name-matching is therefore the strongest signal available
    /// at expansion time, and it is honest about that: a `body` that is not a
    /// view's `body` is accepted here and rejected by the compiler downstream.
    var hasBodyMember: Bool {
        memberBlock.members.contains { member in
            if let variable = member.decl.as(VariableDeclSyntax.self) {
                return variable.bindings.contains { binding in
                    binding.pattern.as(IdentifierPatternSyntax.self)?.identifier.text == "body"
                }
            }
            return false
        }
    }
}

extension DeclGroupSyntax {
    /// A human-readable kind name for diagnostics, carrying its own article
    /// ("an enum", "a class", …).
    ///
    /// `Syntax.kind` renders as `enumDecl`, which leaks the parser's vocabulary
    /// into a message an app author reads, so the common shapes are named
    /// directly and anything else degrades to a generic word rather than to
    /// something misleading.
    ///
    /// The article is part of the value rather than a literal at the
    /// interpolation site because two of these kinds begin with a vowel: a
    /// hardcoded "a" produces "this is a enum" and "this is a actor". Choosing
    /// per-kind here is exact, where any rule applied at the call site would be
    /// guessing from spelling.
    var kindDescription: String {
        switch self {
        case is EnumDeclSyntax: return "an enum"
        case is ClassDeclSyntax: return "a class"
        case is ActorDeclSyntax: return "an actor"
        case is ProtocolDeclSyntax: return "a protocol"
        case is ExtensionDeclSyntax: return "an extension"
        default: return "a declaration"
        }
    }
}

/// Diagnostics `@Verifiable` can emit at its attachment site.
///
/// Spelled as a value type with an explicit `messageID` rather than assembled
/// inline, so the *text* an author sees is a testable constant. A macro whose
/// diagnostics are string literals at the throw site cannot be asserted on
/// without duplicating those literals in the test, which pins the typo rather
/// than the meaning.
enum VerdictMacroDiagnostic: DiagnosticMessage {
    case notAStruct(found: String)
    case noBodyMember

    var message: String {
        switch self {
        case .notAStruct(let found):
            // `found` carries its own article — see `kindDescription`.
            return """
                '@Verifiable' can only be attached to a struct, but this is \(found). \
                SwiftUI views are structs; if this type is a view, declare it as one.
                """
        case .noBodyMember:
            return """
                '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                Add the view's 'body', or remove the attribute.
                """
        }
    }

    var severity: DiagnosticSeverity { .error }

    var diagnosticID: MessageID {
        switch self {
        case .notAStruct:
            return MessageID(domain: "VerdictUIMacros", id: "notAStruct")
        case .noBodyMember:
            return MessageID(domain: "VerdictUIMacros", id: "noBodyMember")
        }
    }
}
