#!/usr/bin/env python3.14
"""Floor compliance check for VerdictUI. Generated by /project-forge.

Run: python3.14 scripts/floor-check.py
     python3.14 scripts/floor-check.py --json
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SLUG = "verdictui"
GAPS = []


def check(path, label):
    p = ROOT / path
    if not p.exists():
        GAPS.append({"item": label, "path": str(p), "status": "missing"})
    return p.exists()


# Core floor
check("CLAUDE.md", "CLAUDE.md")
check("no.md", "no.md")
check(".env.example", ".env.example")


def _check_todo_tracking():
    # Pass if the project has a TODO.md OR is tracked in the Central TODO Store.
    if (ROOT / "TODO.md").exists():
        return
    shared_libs = Path.home() / "Projects" / "shared-libs"
    for extra in (str(shared_libs), str(shared_libs / "pm-base")):
        if extra not in sys.path:
            sys.path.insert(0, extra)
    try:
        import cts_bridge
    except ImportError:
        GAPS.append({"item": "TODO.md", "path": str(ROOT / "TODO.md"), "status": "missing"})
        return
    ok, _detail = cts_bridge.todo_tracking_ok(ROOT)
    if not ok:
        GAPS.append(
            {
                "item": "TODO tracking",
                "path": str(ROOT / "TODO.md"),
                "status": "missing (no CTS record)",
            }
        )


_check_todo_tracking()
check("README.md", "README.md")
check(".gitignore", ".gitignore")
check("docs/goals.md", "docs/goals.md")
check("docs/roadmap.md", "docs/roadmap.md")
check("docs/slo.md", "docs/slo.md")
check("docs/runbook.md", "docs/runbook.md")
check("docs/integrations.md", "docs/integrations.md")
check("docs/ship-readiness.md", "docs/ship-readiness.md")
check("docs/implementation-plan.md", "docs/implementation-plan.md")
# FILE_REGISTRY is fleet-wide floor (Constitution stage_file_registry threshold=0).
if not any(
    (ROOT / p).exists()
    for p in ("docs/FILE_REGISTRY.md", "FILE_REGISTRY.md", "docs/config/FILE_REGISTRY.md")
):
    GAPS.append({"item": "FILE_REGISTRY.md", "path": "docs/FILE_REGISTRY.md", "status": "missing"})
check("contracts/validate-contracts.py", "contracts/")
check("contracts/external-services.md", "contracts/external-services.md")
check(".decisions/INDEX.md", ".decisions/INDEX.md")
check("logs/.gitkeep", "logs/")
check("pm-baselines.json", "pm-baselines.json")
check(f"scripts/{SLUG}-pm.py", "PM script")
check("scripts/dev.sh", "scripts/dev.sh")
check("CHANGELOG.md", "CHANGELOG.md")
check(".projectforge.yml", ".projectforge.yml")

# Swift-specific floor
check("Package.swift", "Package.swift")
check("docs/signing.md", "docs/signing.md")

# @import check
if (ROOT / "CLAUDE.md").exists():
    if "@~/Projects/shared/rules.md" not in (ROOT / "CLAUDE.md").read_text():
        GAPS.append({"item": "@import rules", "path": "CLAUDE.md", "status": "missing"})

# Skills (checked outside root)
skills_root = Path.home() / ".claude/skills"
for skill_dir in [SLUG, f"{SLUG}-audit"]:
    p = skills_root / skill_dir / "SKILL.md"
    if not p.exists():
        GAPS.append({"item": f"skill/{skill_dir}", "path": str(p), "status": "missing"})

# GitHub remote
remote = subprocess.run(
    ["git", "-C", str(ROOT), "remote", "get-url", "origin"],
    capture_output=True,
    text=True,
)
if remote.returncode != 0 or "github.com" not in remote.stdout:
    GAPS.append({"item": "GitHub remote", "path": ".git/config", "status": "missing"})

# CI workflow
ci = ROOT / ".github" / "workflows" / "ci.yml"
if not ci.exists():
    GAPS.append({"item": ".github/workflows/ci.yml", "path": str(ci), "status": "missing"})

# GitHub Actions must be SHA-pinned (supply-chain: mutable @vN tags can be repointed)
_wf = ROOT / ".github" / "workflows"
if _wf.is_dir():
    _uses = re.compile(r"uses:\s*([\w.-]+/[\w./-]+)@(\S+)")
    for _f in _wf.glob("*.y*ml"):
        for _m in _uses.finditer(_f.read_text(encoding="utf-8", errors="ignore")):
            _ref = _m.group(2).split("#")[0].strip()
            if not re.fullmatch(r"[0-9a-f]{40}", _ref) and not _m.group(1).startswith("./"):
                GAPS.append(
                    {
                        "item": f"unpinned action {_m.group(1)}@{_ref} in {_f.name}",
                        "path": str(_f),
                        "status": "not-sha-pinned",
                    }
                )

if "--json" in sys.argv:
    print(json.dumps({"project": "VerdictUI", "gaps": GAPS, "total": len(GAPS)}, indent=2))
else:
    if GAPS:
        print(f"VerdictUI floor: {len(GAPS)} gap(s):")
        for g in GAPS:
            print(f"  ✗ {g['item']}")
    else:
        print("VerdictUI floor: ✓ all checks pass")

sys.exit(1 if GAPS else 0)
