import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import VerdictUIMacros

/// Expansion tests for `#VerdictScenario`.
///
/// These compare generated *source text*, which makes them precise and also
/// makes them the weaker half of the evidence: a macro can emit well-formed
/// source naming a type that does not exist, and a text comparison cannot tell.
/// ``VerdictScenarioCompilationTests`` is the other half — it declares scenarios
/// with the macro for real and hosts them, so the compiler is the oracle.
///
/// The snapshot half is not merely a second opinion, though: for a macro it is
/// often the ONLY layer that can see a regression. SwiftPM rebuilds the plugin
/// but does not re-expand macros in a consuming target whose own sources are
/// unchanged, so a render test can execute a stale expansion and pass against a
/// broken plugin (`no.md` #23, measured).
final class VerdictScenarioMacroTests: XCTestCase {
    private let macros: [String: any Macro.Type] = ["VerdictScenario": VerdictScenarioMacro.self]

    // MARK: - The happy path

    func testTheMacroExpandsToAConformanceAndARegistryEntry() {
        assertMacroExpansion(
            """
            #VerdictScenario("checkout") {
                Text("Total")
            }
            """,
            expandedSource: """
            /// A `VerdictScenario` generated by `#VerdictScenario`.
            struct CheckoutScenario: VerdictScenario, Sendable {
                let name = "checkout"

                @MainActor @ViewBuilder
                func body(state _: ScenarioState) -> some View {
                    Text("Total").verdictProbe("CheckoutScenario.text.0", role: .text, text: "Total")
                }

                /// This scenario's registry entry. Name it in a
                /// `ScenarioRegistry` to make the scenario discoverable.
                static let verdictEntry = ScenarioEntry {
                    CheckoutScenario()
                }
            }
            """,
            macros: macros
        )
    }

    func testTheScenarioBodyIsProbedByTheSameWalkAsAView() {
        // The two macros must instrument identically: an element that is
        // verifiable inside a `@Verifiable` view and invisible inside a
        // `#VerdictScenario` would be a difference with no reason an author
        // could see. Sharing `BodyProbeWalk` is what makes that true, and this
        // pins the observable consequence — same roles, same id shape, same
        // per-role counters.
        //
        // `Button("go") {}` is pinned as printing across two lines with a space
        // before the modifier. That is the lifted-trivia wart documented on
        // `VerifiableMacro.expansion`: an expression moved out of its original
        // position keeps the trivia it had there, and SwiftBasicFormat cannot
        // re-indent lifted code (measured, not assumed). Pinned as what it IS
        // rather than papered over, so a future SwiftSyntax that formats
        // differently shows up as a failure to look at, not as silent drift.
        assertMacroExpansion(
            """
            #VerdictScenario("many") {
                Text("a")
                Text("b")
                Button("go") {}
            }
            """,
            expandedSource: """
            /// A `VerdictScenario` generated by `#VerdictScenario`.
            struct ManyScenario: VerdictScenario, Sendable {
                let name = "many"

                @MainActor @ViewBuilder
                func body(state _: ScenarioState) -> some View {
                    Text("a").verdictProbe("ManyScenario.text.0", role: .text, text: "a")
                    Text("b").verdictProbe("ManyScenario.text.1", role: .text, text: "b")
                    Button("go") {
                    } .verdictProbe("ManyScenario.button.0", role: .button, text: "go")
                }

                /// This scenario's registry entry. Name it in a
                /// `ScenarioRegistry` to make the scenario discoverable.
                static let verdictEntry = ScenarioEntry {
                    ManyScenario()
                }
            }
            """,
            macros: macros
        )
    }

    // MARK: - The name → type-name transform

    func testAMultiWordNameBecomesUpperCamelCase() {
        // Spaces, hyphens and underscores are all word boundaries: a scenario
        // name is written for a human and a type name must be an identifier.
        XCTAssertEqual(
            VerdictScenarioMacro.typeName(forScenarioNamed: "checkout flow"),
            "CheckoutFlowScenario"
        )
        XCTAssertEqual(
            VerdictScenarioMacro.typeName(forScenarioNamed: "checkout-flow"),
            "CheckoutFlowScenario"
        )
        XCTAssertEqual(
            VerdictScenarioMacro.typeName(forScenarioNamed: "checkout_flow"),
            "CheckoutFlowScenario"
        )
    }

    func testTheScenarioSuffixIsAlwaysAppended() {
        // A scenario named "Text" must not generate `struct Text`: inside its
        // own expansion that would shadow SwiftUI's `Text`, so every `Text(…)`
        // in the body would resolve to the scenario itself. The suffix is what
        // makes the generated name unable to collide with the vocabulary the
        // body is written in.
        XCTAssertEqual(VerdictScenarioMacro.typeName(forScenarioNamed: "Text"), "TextScenario")
    }

    func testANameStartingWithADigitIsMadeALegalIdentifier() {
        // Legal in a scenario name, illegal as the first character of a Swift
        // identifier.
        XCTAssertEqual(VerdictScenarioMacro.typeName(forScenarioNamed: "2fa"), "S2faScenario")
    }

    func testANameWithNoIdentifierCharactersHasNoTypeName() {
        // The `nil` the diagnostic below is built on. Mangling this into
        // something like `_Scenario` would collide with the next such name, so
        // the macro reports instead.
        XCTAssertNil(VerdictScenarioMacro.typeName(forScenarioNamed: "---"))
        XCTAssertNil(VerdictScenarioMacro.typeName(forScenarioNamed: ""))
    }

    // MARK: - Diagnostics

    func testAnInterpolatedNameIsReportedRatherThanGuessedAt() {
        // The name becomes both the generated type and the key a verdict is
        // filed under, and neither is knowable at expansion time from an
        // interpolated string. Reported at the use site rather than as an error
        // inside generated code an author cannot see or edit.
        assertMacroExpansion(
            """
            #VerdictScenario("a\\(b)c") {
                Text("x")
            }
            """,
            expandedSource: """
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '#VerdictScenario' needs its name as a plain string literal, because the \
                        name becomes both the generated type and the key a verdict is filed \
                        under — neither is knowable from an interpolated or computed string.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testANameWithNoIdentifierCharactersIsReported() {
        assertMacroExpansion(
            """
            #VerdictScenario("---") {
                Text("x")
            }
            """,
            expandedSource: """
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '#VerdictScenario' cannot build a type name from '---': it contains \
                        no letters or digits. Give the scenario a name with at least one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAMissingBodyClosureIsReported() {
        assertMacroExpansion(
            """
            #VerdictScenario("empty")
            """,
            expandedSource: """
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '#VerdictScenario' needs a trailing closure holding the view to verify. \
                        Write it as '#VerdictScenario("name") { Text("hello") }'.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    // MARK: - The registry

    func testThePluginRegistersTheScenarioMacro() {
        // A macro implemented but unregistered fails at the USE site with
        // "external macro implementation type could not be found", which reads
        // like a toolchain fault. Asserting membership here turns that into a
        // test failure in the module that owns the mistake.
        let registered = VerdictUIMacroPlugin().providingMacros.map { String(describing: $0) }
        XCTAssertTrue(
            registered.contains("VerdictScenarioMacro"),
            "VerdictScenarioMacro is implemented but not listed in the plugin: \(registered)"
        )
    }
}
