import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import VerdictUIMacros

/// Compile-time DIAGNOSTICS for `@Verifiable` and `#VerdictScenario` — the
/// half of the macro surface that reports rather than generates.
///
/// Split from `VerifiableMacroTests` (CTS-E1A2E56A / CTS-5C4D85AB) along the
/// seam the file already had: everything above judged what the macro EMITS,
/// everything here judges what it REFUSES, and the two share only the one-line
/// `macros` dictionary each class declares for itself. That last point is what
/// made this split safe where `no.md` #19 refused one — `ProbeLayoutTests`
/// would have had to widen twelve top-level `private` fixtures to `internal`
/// and collide with a sibling file's same-named `HeadlessHost`, while this file
/// widens nothing.
final class VerifiableMacroDiagnosticsTests: XCTestCase {
    private let macros: [String: any Macro.Type] = [
        "Verifiable": VerifiableMacro.self,
        "VerdictScenario": VerdictScenarioMacro.self,
    ]


    func testTwoElementsSharingAnExplicitIdIsAnError() {
        // An id is what every other layer matches on: `TreeDiff` pairs nodes by
        // it, `DuplicateProbeIDRule` reports on it, and Wave 5's baselines key
        // on it. A collision therefore does not merely look untidy — it merges
        // two elements into one for every consumer downstream.
        //
        // The kernel already catches this at RUNTIME, and that is not a reason
        // to skip it here: a runtime rule needs the view rendered in a scenario
        // somebody remembered to write, while the compiler sees every
        // `@Verifiable` view in the module on every build. Reported as an
        // ERROR rather than a warning because there is no reading under which
        // two elements sharing an id is what the author meant.
        //
        // The diagnostic lands on the SECOND occurrence: the first is where the
        // id was legitimately introduced, and pointing at it would send the
        // reader to the wrong line.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("a").verdictProbe("same-id", role: .text)
                        Text("b").verdictProbe("same-id", role: .text)
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("a").verdictProbe("same-id", role: .text)
                        Text("b").verdictProbe("same-id", role: .text)
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                Text("a").verdictProbe("same-id", role: .text)
                                Text("b").verdictProbe("same-id", role: .text)
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                Text("a").verdictProbe("same-id", role: .text)
                                Text("b").verdictProbe("same-id", role: .text)
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        Two elements in this view both use the probe id 'same-id'. \
                        Ids must be unique within a view: TreeDiff matches nodes by id \
                        and a baseline keys on it, so a collision silently merges the \
                        two elements. Give this one a different id.
                        """,
                    line: 6,
                    column: 13
                )
            ],
            macros: macros
        )
    }

    func testDistinctExplicitIdsAreAccepted() {
        // The control. Without it, "reports a duplicate" is satisfied by an
        // implementation that reports every explicit probe (no.md #12 — an
        // assertion the correct and the broken code both satisfy is not a
        // test). No `diagnostics:` argument means the expansion must be silent.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("a").verdictProbe("id-a", role: .text)
                        Text("b").verdictProbe("id-b", role: .text)
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("a").verdictProbe("id-a", role: .text)
                        Text("b").verdictProbe("id-b", role: .text)
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                Text("a").verdictProbe("id-a", role: .text)
                                Text("b").verdictProbe("id-b", role: .text)
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                Text("a").verdictProbe("id-a", role: .text)
                                Text("b").verdictProbe("id-b", role: .text)
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAnInteractiveElementWithNoLabelIsAWarningCarryingAFixIt() {
        // The plan calls this "an interactive element with no derivable ID".
        // Measured, that is not what happens: `Button(action:) { Image(…) }`
        // DOES get an id (`Row.button.0`). What it has no way to supply is
        // `text:` — the accessible label — because the only literal in it
        // belongs to the nested `Image`. So the real defect is narrower and
        // worth stating precisely: an interactive element the verdict can point
        // at but cannot NAME. `TruncationRule` has nothing to read, no text
        // assertion can reference it, and a human reading the verdict sees an
        // anonymous button among several.
        //
        // A WARNING, not an error: the view is legitimate SwiftUI, it renders,
        // and it is verifiable in every respect except its label. Escalating it
        // would make `@Verifiable` refuse to compile working code, which is how
        // an adoption-focused tool gets removed rather than fixed.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Button(action: save) {
                        Image("gear")
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Button(action: save) {
                        Image("gear")
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Button(action: save) {
                                Image("gear").verdictProbe("Row.image.0", role: .image, text: "gear")
                            } .verdictProbe("Row.button.0", role: .button).verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Button(action: save) {
                                Image("gear").verdictProbe("Row.image.0", role: .image, text: "gear")
                            } .verdictProbe("Row.button.0", role: .button)
                }
            }

            extension Row: VerifiableView {
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        This button has no label the verdict can name it by, so it is \
                        probed as 'Row.button.0' with no text. Add \
                        '.verdictProbe("Row.button.0", role: .button, text: "…")' with the \
                        label a user would read, or give the button a string label.
                        """,
                    line: 4,
                    column: 9,
                    severity: .warning,
                    fixIts: [FixItSpec(message: "Add an explicit probe carrying the button's label")]
                )
            ],
            macros: macros
        )
    }

    func testALabelledButtonIsNotWarnedAbout() {
        // The control for the warning above. `Button("Save")` forwards its
        // literal as `text:`, so the verdict can name it and there is nothing
        // to report — and without this, "warns about an unlabelled button" is
        // satisfied by an implementation that warns about every button.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Button("Save") { save() }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Button("Save") { save() }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Button("Save") {
                        save()
                    } .verdictProbe("Row.button.0", role: .button, text: "Save").verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Button("Save") {
                        save()
                    } .verdictProbe("Row.button.0", role: .button, text: "Save")
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAnExplicitlyProbedUnlabelledButtonIsNotWarnedAbout() {
        // The author has already answered the question the warning asks, so
        // repeating it would be noise — and a lint that fires on code the
        // author has already fixed is the fastest way to get every diagnostic
        // from this macro ignored.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Button(action: save) {
                        Image("gear")
                    }.verdictProbe("save-button", role: .button, text: "Save")
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Button(action: save) {
                        Image("gear")
                    }.verdictProbe("save-button", role: .button, text: "Save")
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Button(action: save) {
                                Image("gear").verdictProbe("Row.image.0", role: .image, text: "gear")
                            } .verdictProbe("save-button", role: .button, text: "Save").verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Button(action: save) {
                                Image("gear").verdictProbe("Row.image.0", role: .image, text: "gear")
                            } .verdictProbe("save-button", role: .button, text: "Save")
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    // MARK: - Misuse is reported at the attachment site

    func testAttachingToAnEnumIsAnErrorNamingTheKind() {
        assertMacroExpansion(
            """
            @Verifiable
            enum Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            expandedSource: """
            enum Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only be attached to a struct, but this is an enum. \
                        SwiftUI views are structs; if this type is a view, declare it as one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAttachingToAClassIsAnErrorNamingTheKind() {
        // A second kind, because a message that interpolates the kind could
        // hardcode "enum" and pass the test above forever.
        assertMacroExpansion(
            """
            @Verifiable
            class Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            expandedSource: """
            class Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only be attached to a struct, but this is a class. \
                        SwiftUI views are structs; if this type is a view, declare it as one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAStructWithNoBodyIsAnError() {
        assertMacroExpansion(
            """
            @Verifiable
            struct NotAView {
                let title: String
            }
            """,
            expandedSource: """
            struct NotAView {
                let title: String
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                        Add the view's 'body', or remove the attribute.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAMemberNamedBodyThatIsNotAPropertyDoesNotSatisfyTheRequirement() {
        // `func body()` is not the view's `body`. The detector looks at variable
        // bindings only, so this must still be the no-body error — a detector
        // matching any member named "body" would accept it and then generate
        // code that fails to compile inside the expansion, which is the
        // diagnostic quality this macro exists to avoid.
        assertMacroExpansion(
            """
            @Verifiable
            struct Thing {
                func body() -> Int { 0 }
            }
            """,
            expandedSource: """
            struct Thing {
                func body() -> Int { 0 }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                        Add the view's 'body', or remove the attribute.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    // MARK: - The registry

    func testThePluginRegistersEveryMacroThisModuleImplements() {
        // A macro implemented but unregistered fails at the USE site with
        // "external macro implementation type could not be found", which reads
        // like a toolchain fault. Asserting membership here turns that into a
        // test failure in the module that owns the mistake.
        let registered = VerdictUIMacroPlugin().providingMacros.map { String(describing: $0) }
        XCTAssertTrue(
            registered.contains("VerifiableMacro"),
            "VerifiableMacro is implemented but not listed in VerdictUIMacroPlugin: \(registered)"
        )
    }
}
