import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import VerdictUIMacros

/// Expansion tests for `@Verifiable`.
///
/// `assertMacroExpansion` compares generated *source text*, which makes these
/// tests precise and also makes them the weaker half of the wave's evidence: a
/// macro can emit perfectly well-formed source that names a type which does not
/// exist, and a text comparison cannot tell. `VerifiableCompilationTests` is the
/// other half — it imports the macro for real and renders the result, so the
/// compiler is the oracle. Neither half alone is sufficient.
final class VerifiableMacroTests: XCTestCase {
    private let macros: [String: any Macro.Type] = ["Verifiable": VerifiableMacro.self]

    // MARK: - The happy path

    func testAttachingToAViewStructGeneratesTheProbedBody() {
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hello")
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hello")
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hello").verdictProbe("Row.text.0", role: .text, text: "hello").verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testTheIdIsDerivedFromTheTypeNameAndTheElementsPosition() {
        // The id is the macro's contract with every other layer: `TreeDiff`
        // matches on it, `DuplicateProbeIDRule` reports on it, and a baseline
        // recorded in Wave 5 keys on it. Two elements of the same role must
        // therefore get distinct, ORDER-STABLE ids — a single counter shared
        // across roles would renumber every element below an inserted one.
        //
        // The expected indentation below looks wrong and is CORRECT as pinned:
        // the expression is lifted out of `body`, so its interior lines keep the
        // indentation they had there. `SwiftBasicFormat` was tried and measured
        // — it supplies trivia only where trivia is absent, so it cannot
        // re-indent lifted code, and stripping first makes it emit flat output.
        // See the note in `VerifiableMacro.expansion`. Do not "fix" this
        // snapshot to look tidy; change the macro or leave it.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("first")
                        Image("icon")
                        Text("second")
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("first")
                        Image("icon")
                        Text("second")
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                        Text("first").verdictProbe("Row.text.0", role: .text, text: "first")
                        Image("icon").verdictProbe("Row.image.0", role: .image, text: "icon")
                        Text("second").verdictProbe("Row.text.1", role: .text, text: "second")
                            } .verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAnElementThatAlreadyHasAProbeIsNotProbedAgain() {
        // The documented contract: an explicit probe wins. Re-probing would give
        // one element two ids and make `DuplicateProbeIDRule` fire on the
        // macro's own output — the instrumentation reporting itself as a defect.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text).verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAModifiedElementIsStillRecognisedThroughItsChain() {
        // Nearly every real element carries modifiers, so a walk that only
        // recognised a bare `Text(...)` would probe almost nothing in a real
        // codebase while passing a test suite written with bare elements.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hi").padding(7).foregroundStyle(.red)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hi").padding(7).foregroundStyle(.red)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hi").padding(7).foregroundStyle(.red).verdictProbe("Row.text.0", role: .text, text: "hi").verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testElementsInsideAModifiedContainerAreStillProbed() {
        // `VStack { ... }.padding()` is the single most common shape in real
        // SwiftUI, and it is structurally different from a bare `VStack { ... }`:
        // the outer call's callee is a MemberAccess whose BASE holds the closure.
        // A walk that recurses only into a call's arguments and trailing closure
        // never reaches that base, so everything inside would go unprobed while
        // a suite written with unmodified containers stayed green.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("inner")
                    }.padding(7)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("inner")
                    }.padding(7)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                        Text("inner").verdictProbe("Row.text.0", role: .text, text: "inner")
                            } .padding(7).verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAnInterpolatedStringIsNotForwardedAsText() {
        // `text:` feeds `TextMetrics`, which the truncation rule reads. An
        // interpolated string is not knowable at expansion time, so forwarding
        // the source text would put the literal `\\(name)` where a rule expects
        // what the user sees — a false value is worse than an absent one,
        // because the rule acts on it.
        assertMacroExpansion(
            #"""
            @Verifiable
            struct Row: View {
                let name: String
                var body: some View {
                    Text("hello \(name)")
                }
            }
            """#,
            expandedSource: #"""
            struct Row: View {
                let name: String
                var body: some View {
                    Text("hello \(name)")
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hello \(name)").verdictProbe("Row.text.0", role: .text).verdictRoot(into: sink)
                }
            }
            """#,
            macros: macros
        )
    }

    func testAMultiStatementBodyIsReportedRatherThanSilentlyLeftUnprobed() {
        // The walk rewrites a single expression. A body it cannot rewrite must
        // SAY so: generating an unprobed passthrough would compile, render, and
        // produce a tree with a root and nothing under it, so every rule would
        // report PASS on a screen nobody instrumented. A false green is this
        // product's worst failure mode.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    let label = "hi"
                    return Text(label)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    let label = "hi"
                    return Text(label)
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only probe a 'body' that is a single expression, and \
                        this one is not. Move the statements into a computed property or a \
                        subview, or probe the elements by hand with '.verdictProbe(_:role:)'.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testTheViewsOwnBodyIsLeftUntouched() {
        // The load-bearing property for adoption: attaching `@Verifiable` must
        // not change how the view renders in a real app. A member macro cannot
        // rewrite `body` — but it could *shadow* it, and the way to be sure it
        // does not is to assert the original text survives verbatim.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("unchanged").padding(7)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("unchanged").padding(7)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("unchanged").padding(7).verdictProbe("Row.text.0", role: .text, text: "unchanged").verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAGenericViewExpandsTheSameWay() {
        // Named as an edge shape by the plan. It is one here because a member
        // macro that tried to restate the type's signature would have to
        // reproduce generic parameters and the where clause correctly; this one
        // does not restate them, and that is the property being pinned.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row<Content: View>: View where Content: Equatable {
                let content: Content
                var body: some View {
                    content
                }
            }
            """,
            expandedSource: """
            struct Row<Content: View>: View where Content: Equatable {
                let content: Content
                var body: some View {
                    content
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    content.verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAGetterOnlyBodyIsAcceptedLikeAComputedProperty() {
        // `var body: some View { ... }` and `var body: some View { get { ... } }`
        // are the same declaration to the compiler but different syntax trees.
        // The detector matches on the binding's identifier, so both must pass —
        // asserted rather than assumed, since a pattern-matching detector is
        // exactly the kind that silently recognises only the spelling its author
        // happened to write (lesson 256).
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    get { Text("x") }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    get { Text("x") }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("x").verdictProbe("Row.text.0", role: .text, text: "x").verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    // MARK: - Misuse is reported at the attachment site

    func testAttachingToAnEnumIsAnErrorNamingTheKind() {
        assertMacroExpansion(
            """
            @Verifiable
            enum Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            expandedSource: """
            enum Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only be attached to a struct, but this is an enum. \
                        SwiftUI views are structs; if this type is a view, declare it as one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAttachingToAClassIsAnErrorNamingTheKind() {
        // A second kind, because a message that interpolates the kind could
        // hardcode "enum" and pass the test above forever.
        assertMacroExpansion(
            """
            @Verifiable
            class Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            expandedSource: """
            class Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only be attached to a struct, but this is a class. \
                        SwiftUI views are structs; if this type is a view, declare it as one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAStructWithNoBodyIsAnError() {
        assertMacroExpansion(
            """
            @Verifiable
            struct NotAView {
                let title: String
            }
            """,
            expandedSource: """
            struct NotAView {
                let title: String
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                        Add the view's 'body', or remove the attribute.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAMemberNamedBodyThatIsNotAPropertyDoesNotSatisfyTheRequirement() {
        // `func body()` is not the view's `body`. The detector looks at variable
        // bindings only, so this must still be the no-body error — a detector
        // matching any member named "body" would accept it and then generate
        // code that fails to compile inside the expansion, which is the
        // diagnostic quality this macro exists to avoid.
        assertMacroExpansion(
            """
            @Verifiable
            struct Thing {
                func body() -> Int { 0 }
            }
            """,
            expandedSource: """
            struct Thing {
                func body() -> Int { 0 }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                        Add the view's 'body', or remove the attribute.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    // MARK: - The registry

    func testThePluginRegistersEveryMacroThisModuleImplements() {
        // A macro implemented but unregistered fails at the USE site with
        // "external macro implementation type could not be found", which reads
        // like a toolchain fault. Asserting membership here turns that into a
        // test failure in the module that owns the mistake.
        let registered = VerdictUIMacroPlugin().providingMacros.map { String(describing: $0) }
        XCTAssertTrue(
            registered.contains("VerifiableMacro"),
            "VerifiableMacro is implemented but not listed in VerdictUIMacroPlugin: \(registered)"
        )
    }
}
