import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import VerdictUIMacros

/// Expansion tests for `@Verifiable`.
///
/// `assertMacroExpansion` compares generated *source text*, which makes these
/// tests precise and also makes them the weaker half of the wave's evidence: a
/// macro can emit perfectly well-formed source that names a type which does not
/// exist, and a text comparison cannot tell. `VerifiableCompilationTests` is the
/// other half — it imports the macro for real and renders the result, so the
/// compiler is the oracle. Neither half alone is sufficient.
final class VerifiableMacroTests: XCTestCase {
    private let macros: [String: any Macro.Type] = ["Verifiable": VerifiableMacro.self]

    // MARK: - The happy path

    func testAttachingToAViewStructGeneratesTheProbedBody() {
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hello")
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hello")
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hello").verdictProbe("Row.text.0", role: .text, text: "hello").verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Text("hello").verdictProbe("Row.text.0", role: .text, text: "hello")
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testTheIdIsDerivedFromTheTypeNameAndTheElementsPosition() {
        // The id is the macro's contract with every other layer: `TreeDiff`
        // matches on it, `DuplicateProbeIDRule` reports on it, and a baseline
        // recorded in Wave 5 keys on it. Two elements of the same role must
        // therefore get distinct, ORDER-STABLE ids — a single counter shared
        // across roles would renumber every element below an inserted one.
        //
        // The expected indentation below looks wrong and is CORRECT as pinned:
        // the expression is lifted out of `body` and each statement carries the
        // leading trivia it had THERE, so interior lines keep their original
        // depth. That trivia is preserved deliberately — it is the only thing
        // separating a closure's `in` from its first statement, and dropping it
        // produced `{ row inText(…)`, which does not compile (see
        // `testElementsInsideAForEachAreProbedAndTheClosureSurvives`).
        // `SwiftBasicFormat` was tried and measured
        // — it supplies trivia only where trivia is absent, so it cannot
        // re-indent lifted code, and stripping first makes it emit flat output.
        // See the note in `VerifiableMacro.expansion`. Do not "fix" this
        // snapshot to look tidy; change the macro or leave it.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("first")
                        Image("icon")
                        Text("second")
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("first")
                        Image("icon")
                        Text("second")
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                Text("first").verdictProbe("Row.text.0", role: .text, text: "first")
                                Image("icon").verdictProbe("Row.image.0", role: .image, text: "icon")
                                Text("second").verdictProbe("Row.text.1", role: .text, text: "second")
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                Text("first").verdictProbe("Row.text.0", role: .text, text: "first")
                                Image("icon").verdictProbe("Row.image.0", role: .image, text: "icon")
                                Text("second").verdictProbe("Row.text.1", role: .text, text: "second")
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAnElementThatAlreadyHasAProbeIsNotProbedAgain() {
        // The documented contract: an explicit probe wins. Re-probing would give
        // one element two ids and make `DuplicateProbeIDRule` fire on the
        // macro's own output — the instrumentation reporting itself as a defect.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text).verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Text("hello").verdictProbe("chosen-by-hand", role: .text)
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAnExplicitProbeOnAContainerDoesNotSwallowItsChildren() {
        // Positional suppression, asserted on the generated TEXT. An explicit
        // probe means "do not probe THIS position", never "stop walking here":
        // the swallowing form produced a tree of exactly one node with no
        // content, which `vacuous-verdict` cannot catch because the container's
        // own probe makes the tree look observed.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("alpha")
                    }.verdictProbe("outer-container", role: .container)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("alpha")
                    }.verdictProbe("outer-container", role: .container)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                Text("alpha").verdictProbe("Row.text.0", role: .text, text: "alpha")
                            } .verdictProbe("outer-container", role: .container).verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                Text("alpha").verdictProbe("Row.text.0", role: .text, text: "alpha")
                            } .verdictProbe("outer-container", role: .container)
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAModifiedElementIsStillRecognisedThroughItsChain() {
        // Nearly every real element carries modifiers, so a walk that only
        // recognised a bare `Text(...)` would probe almost nothing in a real
        // codebase while passing a test suite written with bare elements.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hi").padding(7).foregroundStyle(.red)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hi").padding(7).foregroundStyle(.red)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hi").padding(7).foregroundStyle(.red).verdictProbe("Row.text.0", role: .text, text: "hi").verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Text("hi").padding(7).foregroundStyle(.red).verdictProbe("Row.text.0", role: .text, text: "hi")
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testElementsInsideAModifiedContainerAreStillProbed() {
        // `VStack { ... }.padding()` is the single most common shape in real
        // SwiftUI, and it is structurally different from a bare `VStack { ... }`:
        // the outer call's callee is a MemberAccess whose BASE holds the closure.
        // A walk that recurses only into a call's arguments and trailing closure
        // never reaches that base, so everything inside would go unprobed while
        // a suite written with unmodified containers stayed green.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("inner")
                    }.padding(7)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        Text("inner")
                    }.padding(7)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                Text("inner").verdictProbe("Row.text.0", role: .text, text: "inner")
                            } .padding(7).verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                Text("inner").verdictProbe("Row.text.0", role: .text, text: "inner")
                            } .padding(7)
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAnInterpolatedStringIsNotForwardedAsText() {
        // `text:` feeds `TextMetrics`, which the truncation rule reads. An
        // interpolated string is not knowable at expansion time, so forwarding
        // the source text would put the literal `\\(name)` where a rule expects
        // what the user sees — a false value is worse than an absent one,
        // because the rule acts on it.
        assertMacroExpansion(
            #"""
            @Verifiable
            struct Row: View {
                let name: String
                var body: some View {
                    Text("hello \(name)")
                }
            }
            """#,
            expandedSource: #"""
            struct Row: View {
                let name: String
                var body: some View {
                    Text("hello \(name)")
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("hello \(name)").verdictProbe("Row.text.0", role: .text).verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Text("hello \(name)").verdictProbe("Row.text.0", role: .text)
                }
            }

            extension Row: VerifiableView {
            }
            """#,
            macros: macros
        )
    }

    func testAMultiStatementBodyIsReportedRatherThanSilentlyLeftUnprobed() {
        // The walk rewrites a single expression. A body it cannot rewrite must
        // SAY so: generating an unprobed passthrough would compile, render, and
        // produce a tree with a root and nothing under it, so every rule would
        // report PASS on a screen nobody instrumented. A false green is this
        // product's worst failure mode.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    let label = "hi"
                    return Text(label)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    let label = "hi"
                    return Text(label)
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only probe a 'body' that is a single expression, and \
                        this one is not. Move the statements into a computed property or a \
                        subview, or probe the elements by hand with '.verdictProbe(_:role:)'.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testTheViewsOwnBodyIsLeftUntouched() {
        // The load-bearing property for adoption: attaching `@Verifiable` must
        // not change how the view renders in a real app. A member macro cannot
        // rewrite `body` — but it could *shadow* it, and the way to be sure it
        // does not is to assert the original text survives verbatim.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("unchanged").padding(7)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("unchanged").padding(7)
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("unchanged").padding(7).verdictProbe("Row.text.0", role: .text, text: "unchanged").verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Text("unchanged").padding(7).verdictProbe("Row.text.0", role: .text, text: "unchanged")
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAGenericViewExpandsTheSameWay() {
        // Named as an edge shape by the plan. It is one here because a member
        // macro that tried to restate the type's signature would have to
        // reproduce generic parameters and the where clause correctly; this one
        // does not restate them, and that is the property being pinned.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row<Content: View>: View where Content: Equatable {
                let content: Content
                var body: some View {
                    content
                }
            }
            """,
            expandedSource: """
            struct Row<Content: View>: View where Content: Equatable {
                let content: Content
                var body: some View {
                    content
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    content.verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    content
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testElementsInsideAForEachAreProbedAndTheClosureSurvives() {
        // `ForEach` is the most common list shape in SwiftUI, and it is an edge
        // shape for a syntactic reason: its trailing closure carries a SIGNATURE
        // (`row in`), and the first statement's leading trivia is the only thing
        // separating `in` from that statement. The walk rebuilds each statement
        // from a `.trimmed` expression, so a probe attached here glued the two
        // together — `{ row inText(row.title) }`, which is not Swift at all.
        //
        // The defect is invisible to every test that uses a signature-less
        // closure, which is every other snapshot in this file, so the shape has
        // to be pinned explicitly rather than assumed to follow from the others.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    ForEach(rows) { row in
                        Text(row.title)
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    ForEach(rows) { row in
                        Text(row.title)
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    ForEach(rows) { row in
                                Text(row.title).verdictProbe("Row.text.0", role: .text)
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    ForEach(rows) { row in
                                Text(row.title).verdictProbe("Row.text.0", role: .text)
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testElementsInsideAConditionalBranchAreProbed() {
        // A `@ViewBuilder` conditional is a STATEMENT, not an expression, and the
        // walk rewrites only statements that ARE expressions. So every element in
        // every branch went unprobed — the same false-green shape as the explicit
        // -probe swallow: the surrounding container's probed siblings make the
        // tree look observed, and every rule then reports PASS about branch
        // content nobody instrumented.
        //
        // Both branches are probed, and the id counter runs across them rather
        // than resetting per branch: only one branch renders, so two elements
        // sharing `Row.text.0` would be invisible at runtime and would collide
        // the moment a view rendered both (a conditional inside a ForEach).
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        if isOn {
                            Text("on")
                        } else {
                            Text("off")
                        }
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        if isOn {
                            Text("on")
                        } else {
                            Text("off")
                        }
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                if isOn {
                                    Text("on").verdictProbe("Row.text.0", role: .text, text: "on")
                                } else {
                                    Text("off").verdictProbe("Row.text.1", role: .text, text: "off")
                                }
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                if isOn {
                                    Text("on").verdictProbe("Row.text.0", role: .text, text: "on")
                                } else {
                                    Text("off").verdictProbe("Row.text.1", role: .text, text: "off")
                                }
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testElementsInsideASwitchCaseAreProbed() {
        // The other `@ViewBuilder` statement form. Covered separately from `if`
        // because they are different syntax nodes with no shared supertype the
        // walk can match once — a fix that handles only `if` leaves `switch`
        // silently unprobed, and a suite written with `if` alone stays green.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        switch phase {
                        case .idle:
                            Text("idle")
                        case .busy:
                            Text("busy")
                        }
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        switch phase {
                        case .idle:
                            Text("idle")
                        case .busy:
                            Text("busy")
                        }
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                switch phase {
                                case .idle:
                                    Text("idle").verdictProbe("Row.text.0", role: .text, text: "idle")
                                case .busy:
                                    Text("busy").verdictProbe("Row.text.1", role: .text, text: "busy")
                                }
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                switch phase {
                                case .idle:
                                    Text("idle").verdictProbe("Row.text.0", role: .text, text: "idle")
                                case .busy:
                                    Text("busy").verdictProbe("Row.text.1", role: .text, text: "busy")
                                }
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testANestedCustomViewIsDeferredToTheCompilerWhileItsSiblingsAreProbed() {
        // The plan's "nested custom views" shape. `MyRow()` still gets NO probe
        // of its own — a macro runs on syntax and cannot know a custom type's
        // role, and a wrong role is worse than an absent one because rules act
        // on it. What changed in Task 6 is what happens INSTEAD of nothing.
        //
        // The walk wraps it in `verdictProbing(_:)`, whose two overloads resolve
        // at COMPILE time: the constrained one renders the view's probed content
        // when the type conforms to `VerifiableView` (which `@Verifiable` adds),
        // the passthrough renders it unchanged otherwise. So "nested
        // `@Verifiable` types compose" stopped being a doc-comment promise and
        // became a mechanism — before this, `verdictProbedBody` was generated
        // and NOTHING ever called it, so the two macros over a custom view
        // produced an empty tree and a `vacuous-verdict`.
        //
        // The sibling `Text` is in the same body deliberately: an expansion that
        // probed NOTHING would also satisfy "MyRow carries no probe", so the
        // control is what makes this test able to fail for its own reason.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    VStack {
                        MyRow()
                        Text("after")
                    }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    VStack {
                        MyRow()
                        Text("after")
                    }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    VStack {
                                verdictProbing(MyRow())
                                Text("after").verdictProbe("Row.text.0", role: .text, text: "after")
                            } .verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    VStack {
                                verdictProbing(MyRow())
                                Text("after").verdictProbe("Row.text.0", role: .text, text: "after")
                            }
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }

    func testAGetterOnlyBodyIsAcceptedLikeAComputedProperty() {
        // `var body: some View { ... }` and `var body: some View { get { ... } }`
        // are the same declaration to the compiler but different syntax trees.
        // The detector matches on the binding's identifier, so both must pass —
        // asserted rather than assumed, since a pattern-matching detector is
        // exactly the kind that silently recognises only the spelling its author
        // happened to write (lesson 256).
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    get { Text("x") }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    get { Text("x") }
                }

                /// The view's `body`, probed, with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                @ViewBuilder
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    Text("x").verdictProbe("Row.text.0", role: .text, text: "x").verdictRoot(into: sink)
                }

                /// The view's `body`, probed, with NO root installed.
                ///
                /// Generated by `@Verifiable`, and this is the member that makes the
                /// two macros COMPOSE. `verdictProbedBody(into:)` installs a root,
                /// and nesting one root inside another is unsupported — the inner
                /// viewport reaches the outer collector and every frame is then
                /// measured against the wrong rectangle. A view rendered INSIDE a
                /// scenario is already under `OracleHost`'s root, so it needs the
                /// probed content and nothing else.
                @ViewBuilder
                var verdictProbedContent: some View {
                    Text("x").verdictProbe("Row.text.0", role: .text, text: "x")
                }
            }

            extension Row: VerifiableView {
            }
            """,
            macros: macros
        )
    }
}
