import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import VerdictUIMacros

/// Expansion tests for `@Verifiable`.
///
/// `assertMacroExpansion` compares generated *source text*, which makes these
/// tests precise and also makes them the weaker half of the wave's evidence: a
/// macro can emit perfectly well-formed source that names a type which does not
/// exist, and a text comparison cannot tell. `VerifiableCompilationTests` is the
/// other half — it imports the macro for real and renders the result, so the
/// compiler is the oracle. Neither half alone is sufficient.
final class VerifiableMacroTests: XCTestCase {
    private let macros: [String: any Macro.Type] = ["Verifiable": VerifiableMacro.self]

    // MARK: - The happy path

    func testAttachingToAViewStructGeneratesTheProbedBody() {
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("hello")
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("hello")
                }

                /// The view's `body` with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    body.verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testTheViewsOwnBodyIsLeftUntouched() {
        // The load-bearing property for adoption: attaching `@Verifiable` must
        // not change how the view renders in a real app. A member macro cannot
        // rewrite `body` — but it could *shadow* it, and the way to be sure it
        // does not is to assert the original text survives verbatim.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    Text("unchanged").padding(7)
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    Text("unchanged").padding(7)
                }

                /// The view's `body` with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    body.verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAGenericViewExpandsTheSameWay() {
        // Named as an edge shape by the plan. It is one here because a member
        // macro that tried to restate the type's signature would have to
        // reproduce generic parameters and the where clause correctly; this one
        // does not restate them, and that is the property being pinned.
        assertMacroExpansion(
            """
            @Verifiable
            struct Row<Content: View>: View where Content: Equatable {
                let content: Content
                var body: some View {
                    content
                }
            }
            """,
            expandedSource: """
            struct Row<Content: View>: View where Content: Equatable {
                let content: Content
                var body: some View {
                    content
                }

                /// The view's `body` with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    body.verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    func testAGetterOnlyBodyIsAcceptedLikeAComputedProperty() {
        // `var body: some View { ... }` and `var body: some View { get { ... } }`
        // are the same declaration to the compiler but different syntax trees.
        // The detector matches on the binding's identifier, so both must pass —
        // asserted rather than assumed, since a pattern-matching detector is
        // exactly the kind that silently recognises only the spelling its author
        // happened to write (lesson 256).
        assertMacroExpansion(
            """
            @Verifiable
            struct Row: View {
                var body: some View {
                    get { Text("x") }
                }
            }
            """,
            expandedSource: """
            struct Row: View {
                var body: some View {
                    get { Text("x") }
                }

                /// The view's `body` with the VerdictUI root installed.
                ///
                /// Generated by `@Verifiable`. Inert until a `VerdictTreeSink` is
                /// attached, so this is a normal view everywhere else.
                func verdictProbedBody(into sink: VerdictTreeSink) -> some View {
                    body.verdictRoot(into: sink)
                }
            }
            """,
            macros: macros
        )
    }

    // MARK: - Misuse is reported at the attachment site

    func testAttachingToAnEnumIsAnErrorNamingTheKind() {
        assertMacroExpansion(
            """
            @Verifiable
            enum Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            expandedSource: """
            enum Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only be attached to a struct, but this is an enum. \
                        SwiftUI views are structs; if this type is a view, declare it as one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAttachingToAClassIsAnErrorNamingTheKind() {
        // A second kind, because a message that interpolates the kind could
        // hardcode "enum" and pass the test above forever.
        assertMacroExpansion(
            """
            @Verifiable
            class Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            expandedSource: """
            class Thing {
                var body: some View {
                    Text("x")
                }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' can only be attached to a struct, but this is a class. \
                        SwiftUI views are structs; if this type is a view, declare it as one.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAStructWithNoBodyIsAnError() {
        assertMacroExpansion(
            """
            @Verifiable
            struct NotAView {
                let title: String
            }
            """,
            expandedSource: """
            struct NotAView {
                let title: String
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                        Add the view's 'body', or remove the attribute.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    func testAMemberNamedBodyThatIsNotAPropertyDoesNotSatisfyTheRequirement() {
        // `func body()` is not the view's `body`. The detector looks at variable
        // bindings only, so this must still be the no-body error — a detector
        // matching any member named "body" would accept it and then generate
        // code that fails to compile inside the expansion, which is the
        // diagnostic quality this macro exists to avoid.
        assertMacroExpansion(
            """
            @Verifiable
            struct Thing {
                func body() -> Int { 0 }
            }
            """,
            expandedSource: """
            struct Thing {
                func body() -> Int { 0 }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: """
                        '@Verifiable' needs a 'body' to wrap, and this type declares none. \
                        Add the view's 'body', or remove the attribute.
                        """,
                    line: 1,
                    column: 1
                )
            ],
            macros: macros
        )
    }

    // MARK: - The registry

    func testThePluginRegistersEveryMacroThisModuleImplements() {
        // A macro implemented but unregistered fails at the USE site with
        // "external macro implementation type could not be found", which reads
        // like a toolchain fault. Asserting membership here turns that into a
        // test failure in the module that owns the mistake.
        let registered = VerdictUIMacroPlugin().providingMacros.map { String(describing: $0) }
        XCTAssertTrue(
            registered.contains("VerifiableMacro"),
            "VerifiableMacro is implemented but not listed in VerdictUIMacroPlugin: \(registered)"
        )
    }
}
